[personal]
first_name = "Nikhil"
last_name = "V"
profile_image = "profile_pic.jpg"
language = "en"
include_icons = true

[personal.info]
address = "House No. 60, Veluthedathuparambil, Haritha Residency, Arakulam P.O, Thodupuzha, Idukki, Kerala, 685591"
telephone = "+91 807 87 94652"

[personal.info.email]
link = "mailto:nikhilvwastaken@gmail.com"
label = "nikhilvwastaken@gmail.com"

[personal.info.linkedin]
link = "https://www.linkedin.com/in/nikhil-v-aa8a5227b"
label = "linkedin.com/nikhilv"

[personal.info.github]
link = "https://github.com/Nikhil-krn"
label = "My github repositories"

[personal.icon]
address = "../assets/iconLibrary/house.svg"
telephone = "../assets/iconLibrary/phone.svg"
email = "../assets/iconLibrary/envelope.svg"
linkedin = "../assets/iconLibrary/logoLinkedin.svg"
github = "../assets/iconLibrary/github.svg"
homepage = "../assets/iconLibrary/globe.svg"

[personal.ia]
inject_ai_prompt = false
inject_keywords = false

[section.icon]
education = "../assets/iconLibrary/education.svg"
experience = "../assets/iconLibrary/experience.svg"
languages = "../assets/iconLibrary/language.svg"
other_experience = "../assets/iconLibrary/cog.svg"
personal = "../assets/iconLibrary/brain.svg"
profile = "../assets/iconLibrary/profile.svg"
references = "../assets/iconLibrary/references.svg"
skills = "../assets/iconLibrary/cog.svg"

[layout]
fill_color = "#FFFFFF"
paper_size = "a4"
accent_color = "#D4D2CC"
left_pane_width = "71%"

[layout.text]
font = "HK Grotesk"
size = "10pt"
cover_letter_size = "11pt"

[layout.text.color]
light = "#EDEDEF"
medium = "#78787E"
dark = "3C3C42"

[language.en]
subtitle = ""
ai_prompt = ""
cv_document_name = "Nikhil's Résumé"
cover_letter_document_name = "Covering letter"

[import]
fontawesome = "@preview/fontawesome:0.6.0"